### ISSUE TITLE
Container doesnt start because of unmet python dependencies

### ISSUE THREAD

**Issue by uvatbc** [Chorss/docker-pgAdmin4#12]
```
GID=50
UID=1000
usermod: no changes
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgAdmin4.py", line 67, in <module>
    app = create_app()
  File "/usr/local/lib/python3.6/site-packages/pgadmin4/pgadmin/__init__.py", line 569, in create_app
    from flask_htmlmin import HTMLMIN
ModuleNotFoundError: No module named 'flask_htmlmin'
```
Fix required:
```
pip install flask_htmlmin
```
Confirmed using:
```
docker run -it --name saveit chorss/docker-pgadmin4 pip install flask_htmlmin
docker commit saveit chorss/docker-pgadmin4
docker run --rm -it chorss/docker-pgadmin4
```

**Comment by Chorss** [comment]
This bug is fixed

**Comment by uvatbc** [comment]
Thanks!
